#!/bin/bash
# INIT script to start / stop PerlShareServer
# Prerequisite for PerlShareServer to work is that apache2 is configured right
# and that it is stared.

test -f /lib/lsb/init-functions || exit 1
. /lib/lsb/init-functions

test -d /etc/perlshare || exit 0

case "$1" in
  start)
    log_begin_msg "Starting PerlShareServer"
    /usr/bin/PerlShareServer.pl >/var/log/perlshare.log 2>&1 &
    log_end_msg 0
    ;;
  stop)
    log_begin_msg "Stopping PerlShareServer"
    DIR=`grep commands /etc/perlshare/config.ini | sed -e 's/[^=]*//'`
    touch $DIR/quit
    log_end_msg 0
    ;;
  *)
  ;;
esac
        

