#!/bin/bash
### BEGIN INIT INFO
# Provides:        perlshare
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1 6
# Short-Description: Start PerlShareServer
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

test -f /lib/lsb/init-functions || exit 1
. /lib/lsb/init-functions

test -d /etc/perlshare || exit 0

case "$1" in
  start)
    log_begin_msg "Starting PerlShareServer"
    perl -I /usr/share/perlshare /usr/share/perlshare/PerlShareServer.pl /etc/perlshare/config.ini >/var/log/perlshare.log 2>&1 &
    log_end_msg 0
    ;;
  stop)
    log_begin_msg "Stopping PerlShareServer"
    DIR=`grep commands /etc/perlshare/config.ini | sed -e 's/[^=]*//'`
    touch $DIR/quit
    log_end_msg 0
    ;;
  *)
  ;;
esac

